[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/resume.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment; filename=\"Nikhil_Bajantri_Resume.pdf\""
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
